/**
 * Centralized UI strings for FabriqWorld. Use these for all user-facing copy
 * so that localization (i18n) can be added later by swapping this module.
 */
export const Strings = {
  app: {
    name: 'FabriqWorld',
  },
  auth: {
    login: 'Login',
    signIn: 'Sign in to continue',
    email: 'Email',
    password: 'Password',
    loginSuccess: 'Login successful!',
    pleaseEnterEmailPassword: 'Please enter email and password',
    networkError: 'Network error. Check your internet connection and try again.',
    somethingWentWrong: 'Something went wrong',
  },
  common: {
    cancel: 'Cancel',
    done: 'Done',
    menu: 'Menu',
    logout: 'Logout',
    lightMode: 'Light Mode',
    darkMode: 'Dark Mode',
    mockData: 'Mock Data',
    liveData: 'Live Data',
    noPrinterConnected: 'No printer connected',
    print: 'Print',
    selectPrinter: 'Select Printer',
    selectCompany: 'Select company',
    addItem: 'Add item',
    returnItem: 'Return item',
    checkout: 'Checkout',
    company: 'Company',
    redirecting: 'Redirecting...',
    creatingOrder: 'Creating order…',
  },
  home: {
    yourSchools: 'Your Schools',
    noCompaniesYet: 'No companies yet',
  },
  explore: {
    comingSoon: 'Coming Soon',
    comingSoonSubtitle: 'Exciting features are on the way. Stay tuned!',
  },
  company: {
    inventory: 'Inventory',
    sales: 'Sales',
    createOrder: 'Create Order',
    transfer: 'Transfer',
    addProducts: 'Add Products',
    requestedItems: 'Requested Items',
    inventoryDescription: 'View products & stock levels',
    salesDescription: 'View past orders & revenue',
    createOrderDescription: 'Start a new order',
    transferDescription: 'Transfer stock between companies',
    addProductsDescription: 'Add products to catalog',
    requestedItemsDescription: 'View & fulfill pending item requests',
    noTilesAvailable: 'No tiles available',
    orders: 'Orders',
    orderDetails: 'Order details',
    orderDetailsPrintNeedItems: 'Wait for items to load, or try opening the order again.',
    /** Sales order list cell when `customer_details` is present. */
    orderListBuyerDetailsPrefix: 'Buyer Details: ',
    /** Sales order list cell when `notes` is present. */
    orderListCommentPrefix: 'Comment: ',
    totalOrders: 'Total Orders',
    all: 'All',
    success: 'Success',
    failed: 'Failed',
    pending: 'Pending',
    refundTab: 'Refunds',
    cashTab: 'Cash',
    onlineTab: 'Online',
    noOrdersFound: 'No orders found',
    uniformGroupTop: 'Top',
    uniformGroupBottom: 'Bottom',
    uniformGroupAccessory: 'Accessory',
    uniformGroupOveralls: 'Overalls',
    uniformGroupGeneric: 'Generic',
    today: 'Today',
    yesterday: 'Yesterday',
    totalSales: 'Total Sales',
    totalRefunds: 'Total Refunds',
    cashSales: 'Cash',
    onlineSales: 'Online',
    customRange: 'Custom Range',
    filterByDate: 'Filter by Date',
    last3Days: 'Last 3 Days',
    last7Days: '7 Days',
    last1Month: '1 Month',
    dateRangeCalendarHint: 'Tap a start date, then an end date on the calendar.',
    clearFilter: 'Clear Filter',
    applyFilter: 'Apply Filter',
    exportPdf: 'Export PDF',
    exportPdfTitle: 'Export sales to PDF',
    exportPdfDownload: 'Download PDF',
    exportPdfEmpty: 'No orders in this range.',
    exportPdfSuccess: 'PDF downloaded.',
    exportPdfError: 'Could not export. Try again.',
    exportPdfCustomInvalid: 'Select a start and end date on the calendar.',
    from: 'From',
    to: 'To',
    loadingMore: 'Loading more…',
    refunds: 'Refunds',
    available: 'Available',
    /** Inventory cell when available qty is 0. */
    productNotAvailable: 'Not available',
    /** Inventory cell when 0 < available < low-stock threshold. */
    productStockLow: 'Product stock low',
    cartEmpty: 'Cart is empty. Tap Add item or Return item to scan or search.',
    item: 'item',
    items: 'items',
    refund: 'Refund',
    /** Short cart / checkout line badge (sale vs request line item). */
    requestBadge: 'Request',
    itemLineRequested: 'Requested',
    itemLineRefunded: 'Refunded',
    collectPayment: 'Collect Payment',
    choosePaymentMethod: 'Choose payment method for this order',
    cash: 'Cash',
    online: 'Online',
    onlinePg: 'Online (PG)',
    split: 'Split',
    completeOrder: 'Complete Order',
    reviewAndCollect: 'Review items & collect payment',
    completeRefundOrder: 'Complete this refund order',
    ordersRequestedItemsA11y: 'Open requested items',
    checkoutOrderNotesLabel: 'Order notes',
    checkoutOrderNotesPlaceholder: 'Add a note for this order (optional)',
    checkoutBuyerDetailsTitle: 'Buyer details',
    checkoutBuyerStudentName: 'Student name *',
    checkoutBuyerStudentClass: 'Student class *',
    checkoutBuyerParentName: 'Parent name',
    checkoutBuyerParentPhone: 'Parent number',
    /** When buyer details block is shown: name + class required before payment. */
    checkoutStudentClassRequiredToast: 'Enter student name and class before taking payment.',
    /** Checkout footer: total unit count (sum of quantities). */
    checkoutTotalItemsEquals: 'Total Items =',
    checkoutTotalAmountEquals: 'Total Amount =',
    onlyAvailable: 'Only {count} available (stock − reserved)',
    reduceQuantity: 'Reduce quantity for items exceeding available stock',
    receipt: 'Receipt',
    receiptSentToPrinter: 'Receipt sent to printer.',
    printFailed: 'Print failed. Try connecting again.',
    /** Receipt screen: Bluetooth adapter off (banner + toast). */
    receiptBluetoothOff: 'Turn on Bluetooth to print receipts.',
    /** Receipt footer when no printer chosen yet (BT on). */
    receiptChoosePrinter: 'Choose printer',
    /** After selecting a printer in the modal (toast / optional caption). */
    receiptPrinterReady: 'Printer ready',
    receiptResetPrinter: 'Reset',
    /** Printer modal: list explanation (this scan may include paired devices). */
    receiptPrinterScanListHint:
      'These printers are from this scan (may include paired devices). Tap one to connect for this receipt.',
    receiptPrinterModalHint:
      'Turn on your receipt printer and ensure Bluetooth is enabled on this device.',
    receiptScanningPrinters: 'Scanning for printers…',
    receiptPrinterModalNoDevices: 'No printers found',
    receiptPrinterModalEmptyHint:
      'Turn on your receipt printer, put it in pairing mode if needed, then tap Scan again.',
    receiptScanAgain: 'Scan again',
    receiptPrinterConnectOrPrintFailed: 'Could not connect or print. Try again.',
    receiptPrinterScanFailed: 'Could not scan for printers. Check Bluetooth permissions.',
    sellerName: 'Fabriq',
    orderCouldNotBeCompleted: 'Order could not be completed. Please try again.',
    pleaseSignInToPlaceOrder: 'Please sign in to place an order.',
    orderPlacedSuccess: 'Order placed successfully.',
    somethingWentWrongTryAgain: 'Something went wrong. Please try again.',
    inventoryTransfer: 'Inventory Transfer',
    createTransfer: 'Create Transfer',
    requests: 'Requests',
    history: 'History',
    noPendingRequests: 'No pending requests',
    noTransferHistory: 'No transfer history',
    noItemsTapToAdd: 'No items. Tap Add item to select products.',
    initiateTransfer: 'Initiate transfer',
    destination: 'Destination',
    destinationCompany: 'Destination company',
    selectProduct: 'Select product',
    total: 'Total',
    payment: 'Payment',
    receiptFootnote: 'All payments are made in Indian National Rupee.',
    /**
     * Thermal printers (CP437): use ASCII-only markers on item lines.
     * Keep Latin characters; avoid scripts that won’t encode on receipt paper.
     */
    receiptPrintRefundMark: '[REFUND]',
    receiptPrintRequestMark: '[REQUEST]',
    requestedOrdersTitle: 'Requested Items',
    unfulfilledOrders: 'Unfulfilled',
    fulfilledOrders: 'Fulfilled',
    searchByStudent: 'Search requests',
    requestItemStudentNameRequired: 'Student name *',
    requestItemStudentClassRequired: 'Class *',
    requestItemPhoneOptional: 'Phone number',
    requestSearchClassLabel: 'Student Class',
    requestSearchStudentLabel: 'Student name',
    requestSearchPhoneLabel: 'Phone number',
    requestSearchSubmit: 'Search',
    requestSearchClear: 'Clear filters',
    noRequestedOrders: 'No orders match this filter',
    noRequestedOrdersWithSearch: 'No orders match your search.',
    requestedOrdersSearchAgain: 'Search again',
    requestedOrdersClearSearch: 'Clear search',
    requestLineDetails: 'Request details',
    student: 'Student',
    classLabel: 'Class',
    phone: 'Phone',
    fulfillmentStatus: 'Status',
    fulfillRequest: 'Fulfill',
    fulfillConfirmMessage: 'Are you sure want to do this, this is irreversible action',
    requestsMarkedFulfilled: 'Requests marked as fulfilled.',
    nothingToFulfill: 'No pending lines to update.',
    multipleStudentsNote: 'Multiple students on this order',
    articleCode: 'Code',
    size: 'Size',
    productNotFound: 'Product not found',
    productNotFoundHint: 'Try another barcode or search by name.',
    couldNotAddInsufficientQuantity: "Couldn't add, as not enough quantity.",
    /** Header on Create Order — park current cart and start empty. */
    createAnotherOrderHeader: 'Save & new',
    /** Header on Create Order — open list of locally saved (not submitted) orders. */
    viewLocalOrdersHeader: 'Saved',
    createAnotherOrderA11y: 'Save current cart and start a new order',
    viewLocalOrdersA11y: 'View orders saved on this device, not yet submitted',
    localDraftsModalTitle: 'Orders not submitted',
    localDraftsEmpty:
      'Nothing saved yet. When a buyer needs more time, tap Save & new to park this cart and start another.',
    localDraftsMaxReached:
      'You can save up to 5 orders on this device. Remove one from Saved to add another.',
    localDraftsNothingToSave: 'Add items to the cart before saving.',
    localDraftSavedToast: 'Order saved on this device. You can start a new one.',
    localDraftContinue: 'Continue',
    localDraftDelete: 'Delete',
    localDraftDeleteConfirmTitle: 'Delete this saved order?',
    localDraftDeleteConfirmMessage: 'It will be removed from this device. This cannot be undone.',
    localDraftReplaceTitle: 'Replace current cart?',
    localDraftReplaceMessage:
      'Your current cart will be cleared and replaced with the saved order.',
    localDraftReplaceConfirm: 'Replace',
    localDraftSummaryLine: '{count} items · {total}',
    localDraftJustNow: 'Just now',
    localDraftMinutesAgo: '{n}m ago',
    localDraftHoursAgo: '{n}h ago',
    localDraftDaysAgo: '{n}d ago',
  },
  errors: {
    generic: 'Something went wrong',
  },
} as const;

export type StringsType = typeof Strings;
