/**
 * Centralized UI strings for FabriqWorld. Use these for all user-facing copy
 * so that localization (i18n) can be added later by swapping this module.
 */
export const Strings = {
  app: {
    name: 'FabriqWorld',
  },
  auth: {
    login: 'Login',
    signIn: 'Sign in to continue',
    email: 'Email',
    password: 'Password',
    loginSuccess: 'Login successful!',
    pleaseEnterEmailPassword: 'Please enter email and password',
    networkError: 'Network error. Check your internet connection and try again.',
    somethingWentWrong: 'Something went wrong',
  },
  common: {
    cancel: 'Cancel',
    done: 'Done',
    menu: 'Menu',
    logout: 'Logout',
    lightMode: 'Light Mode',
    darkMode: 'Dark Mode',
    mockData: 'Mock Data',
    liveData: 'Live Data',
    noPrinterConnected: 'No printer connected',
    print: 'Print',
    selectPrinter: 'Select Printer',
    selectCompany: 'Select company',
    addItem: 'Add item',
    returnItem: 'Return item',
    checkout: 'Checkout',
    company: 'Company',
    redirecting: 'Redirecting...',
    creatingOrder: 'Creating order…',
  },
  home: {
    yourSchools: 'Your Schools',
    noCompaniesYet: 'No companies yet',
  },
  explore: {
    comingSoon: 'Coming Soon',
    comingSoonSubtitle: 'Exciting features are on the way. Stay tuned!',
  },
  company: {
    inventory: 'Inventory',
    sales: 'Sales',
    createOrder: 'Create Order',
    transfer: 'Transfer',
    addProducts: 'Add Products',
    requestedItems: 'Requested Items',
    inventoryDescription: 'View products & stock levels',
    salesDescription: 'View past orders & revenue',
    createOrderDescription: 'Start a new order',
    transferDescription: 'Transfer stock between companies',
    addProductsDescription: 'Add products to catalog',
    requestedItemsDescription: 'View & fulfill pending item requests',
    noTilesAvailable: 'No tiles available',
    orders: 'Orders',
    orderDetails: 'Order details',
    totalOrders: 'Total Orders',
    all: 'All',
    success: 'Success',
    failed: 'Failed',
    pending: 'Pending',
    refundTab: 'Refunds',
    cashTab: 'Cash',
    onlineTab: 'Online',
    noOrdersFound: 'No orders found',
    today: 'Today',
    yesterday: 'Yesterday',
    totalSales: 'Total Sales',
    totalRefunds: 'Total Refunds',
    cashSales: 'Cash',
    onlineSales: 'Online',
    customRange: 'Custom Range',
    filterByDate: 'Filter by Date',
    last3Days: 'Last 3 Days',
    clearFilter: 'Clear Filter',
    applyFilter: 'Apply Filter',
    from: 'From',
    to: 'To',
    loadingMore: 'Loading more…',
    refunds: 'Refunds',
    available: 'Available',
    productStockLow: 'Product stock low',
    cartEmpty: 'Cart is empty. Tap Add item or Return item to scan or search.',
    item: 'item',
    items: 'items',
    refund: 'Refund',
    /** Short cart / checkout line badge (sale vs request line item). */
    requestBadge: 'Request',
    itemLineRequested: 'Requested',
    itemLineRefunded: 'Refunded',
    collectPayment: 'Collect Payment',
    choosePaymentMethod: 'Choose payment method for this order',
    cash: 'Cash',
    online: 'Online',
    onlinePg: 'Online (PG)',
    split: 'Split',
    completeOrder: 'Complete Order',
    reviewAndCollect: 'Review items & collect payment',
    completeRefundOrder: 'Complete this refund order',
    onlyAvailable: 'Only {count} available (stock − reserved)',
    reduceQuantity: 'Reduce quantity for items exceeding available stock',
    receipt: 'Receipt',
    receiptSentToPrinter: 'Receipt sent to printer.',
    printFailed: 'Print failed. Try connecting again.',
    sellerName: 'Fabriq',
    orderCouldNotBeCompleted: 'Order could not be completed. Please try again.',
    pleaseSignInToPlaceOrder: 'Please sign in to place an order.',
    orderPlacedSuccess: 'Order placed successfully.',
    somethingWentWrongTryAgain: 'Something went wrong. Please try again.',
    inventoryTransfer: 'Inventory Transfer',
    createTransfer: 'Create Transfer',
    requests: 'Requests',
    history: 'History',
    noPendingRequests: 'No pending requests',
    noTransferHistory: 'No transfer history',
    noItemsTapToAdd: 'No items. Tap Add item to select products.',
    initiateTransfer: 'Initiate transfer',
    destination: 'Destination',
    destinationCompany: 'Destination company',
    selectProduct: 'Select product',
    total: 'Total',
    payment: 'Payment',
    receiptFootnote: 'All payments are made in Indian National Rupee.',
    /**
     * Thermal printers (CP437): use ASCII-only markers on item lines.
     * Keep Latin characters; avoid scripts that won’t encode on receipt paper.
     */
    receiptPrintRefundMark: '[REFUND]',
    receiptPrintRequestMark: '[REQUEST]',
    requestedOrdersTitle: 'Requested Items',
    unfulfilledOrders: 'Unfulfilled',
    fulfilledOrders: 'Fulfilled',
    searchByStudent: 'Search requests',
    requestItemStudentNameRequired: 'Student name *',
    requestItemStudentClassRequired: 'Class *',
    requestItemPhoneOptional: 'Phone number',
    requestSearchClassLabel: 'Student Class',
    requestSearchStudentLabel: 'Student name',
    requestSearchPhoneLabel: 'Phone number',
    requestSearchSubmit: 'Search',
    requestSearchClear: 'Clear filters',
    noRequestedOrders: 'No orders match this filter',
    noRequestedOrdersWithSearch: 'No orders match your search.',
    requestedOrdersSearchAgain: 'Search again',
    requestedOrdersClearSearch: 'Clear search',
    requestLineDetails: 'Request details',
    student: 'Student',
    classLabel: 'Class',
    phone: 'Phone',
    fulfillmentStatus: 'Status',
    fulfillRequest: 'Fulfill request',
    fulfillRequestHint: 'Marks all pending lines in this order as fulfilled.',
    requestsMarkedFulfilled: 'Requests marked as fulfilled.',
    nothingToFulfill: 'No pending lines to update.',
    multipleStudentsNote: 'Multiple students on this order',
    articleCode: 'Code',
    size: 'Size',
    productNotFound: 'Product not found',
    productNotFoundHint: 'Try another barcode or search by name.',
    couldNotAddInsufficientQuantity: "Couldn't add, as not enough quantity.",
  },
  errors: {
    generic: 'Something went wrong',
  },
} as const;

export type StringsType = typeof Strings;
