/**
 * Centralized UI strings for FabriqWorld. Use these for all user-facing copy
 * so that localization (i18n) can be added later by swapping this module.
 */
export const Strings = {
  app: {
    name: 'FabriqWorld',
  },
  auth: {
    login: 'Login',
    signIn: 'Sign in to continue',
    email: 'Email',
    password: 'Password',
    loginSuccess: 'Login successful!',
    pleaseEnterEmailPassword: 'Please enter email and password',
    networkError: 'Network error. Check your internet connection and try again.',
    somethingWentWrong: 'Something went wrong',
  },
  common: {
    cancel: 'Cancel',
    done: 'Done',
    menu: 'Menu',
    logout: 'Logout',
    lightMode: 'Light Mode',
    darkMode: 'Dark Mode',
    mockData: 'Mock Data',
    liveData: 'Live Data',
    noPrinterConnected: 'No printer connected',
    print: 'Print',
    selectPrinter: 'Select Printer',
    selectCompany: 'Select company',
    addItem: 'Add item',
    returnItem: 'Return item',
    checkout: 'Checkout',
    company: 'Company',
    redirecting: 'Redirecting...',
    creatingOrder: 'Creating order…',
  },
  home: {
    yourSchools: 'Your Schools',
    noCompaniesYet: 'No companies yet',
  },
  explore: {
    comingSoon: 'Coming Soon',
    comingSoonSubtitle: 'Exciting features are on the way. Stay tuned!',
  },
  company: {
    inventory: 'Inventory',
    sales: 'Sales',
    createOrder: 'Create Order',
    transfer: 'Transfer',
    addProducts: 'Add Products',
    inventoryDescription: 'View products & stock levels',
    salesDescription: 'View past orders & revenue',
    createOrderDescription: 'Start a new order',
    transferDescription: 'Transfer stock between companies',
    addProductsDescription: 'Add products to catalog',
    noTilesAvailable: 'No tiles available',
    orders: 'Orders',
    orderDetails: 'Order details',
    totalOrders: 'Total Orders',
    all: 'All',
    success: 'Success',
    failed: 'Failed',
    pending: 'Pending',
    noOrdersFound: 'No orders found',
    available: 'Available',
    productStockLow: 'Product stock low',
    cartEmpty: 'Cart is empty. Tap Add item or Return item to scan or search.',
    item: 'item',
    items: 'items',
    refund: 'Refund',
    collectPayment: 'Collect Payment',
    choosePaymentMethod: 'Choose payment method for this order',
    cash: 'Cash',
    online: 'Online',
    onlinePg: 'Online (PG)',
    split: 'Split',
    completeOrder: 'Complete Order',
    reviewAndCollect: 'Review items & collect payment',
    completeRefundOrder: 'Complete this refund order',
    onlyAvailable: 'Only {count} available (stock − reserved)',
    reduceQuantity: 'Reduce quantity for items exceeding available stock',
    receipt: 'Receipt',
    receiptSentToPrinter: 'Receipt sent to printer.',
    printFailed: 'Print failed. Try connecting again.',
    sellerName: 'Fabriq',
    orderCouldNotBeCompleted: 'Order could not be completed. Please try again.',
    pleaseSignInToPlaceOrder: 'Please sign in to place an order.',
    orderPlacedSuccess: 'Order placed successfully.',
    somethingWentWrongTryAgain: 'Something went wrong. Please try again.',
    inventoryTransfer: 'Inventory Transfer',
    createTransfer: 'Create Transfer',
    requests: 'Requests',
    history: 'History',
    noPendingRequests: 'No pending requests',
    noTransferHistory: 'No transfer history',
    noItemsTapToAdd: 'No items. Tap Add item to select products.',
    initiateTransfer: 'Initiate transfer',
    destination: 'Destination',
    destinationCompany: 'Destination company',
    selectProduct: 'Select product',
    total: 'Total',
    payment: 'Payment',
    receiptFootnote: 'All payments are made in Indian National Rupee.',
  },
  errors: {
    generic: 'Something went wrong',
  },
} as const;

export type StringsType = typeof Strings;
